### ISSUE TITLE
Specification of visible or occluded landmark

### ISSUE THREAD

**Issue by AruniRC** [mtli/BFFL#2]
Some face datasets like COFW have a "visible" annotation to differentiate between visible and occluded landmark. Does your codebase have any way of distinguishing which predicted landmarks are actually visible, and which are occluded?
thanks!

**Comment by mtli** [comment]
Hi, this feature is not implemented. But this can be realized with our label transfer idea explained in the paper. For example, if you have some training examples (or classes in the exemplar class setting) with occlusion tags (can be synthetically generated), you can transfer those labels to test images for free with the prediction.

**Comment by AruniRC** [comment]
Okay, thank you for the info.
